# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1df_-B79NTXa7T_7gAQNS0tKkJVmmG3G6
"""

import pandas as pd

pip install pd

df = pd.read_csv('/GlobalWeatherRepository.csv')

num_duplicates = df.duplicated().sum()
print(f"/n Number of duplicate rows : {num_duplicates}")

avg_temp_by_country = ( df.groupby('country')['temperature_celsius'] .mean().sort_values(ascending=False))
print("/n Average Temperature by Country (Top 5):")
print(avg_temp_by_country.head(5))

avg_temp = df['temperature_celsius'].mean()
print(avg_temp)

min_temp = df['temperature_celsius'].min()
print(min_temp)

max_temp = df['temperature_celsius'].max()
print(max_temp)

top_conditions = df['condition_text'].value_counts().head(3)
print(top_conditions)

df.sort_values('temperature_celsius')

df['location_name'].str.upper()