"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1df_-B79NTXa7T_7gAQNS0tKkJVmmG3G6
"""

import pandas as pd

pip install pd

df = pd.read_csv('/content/GlobalWeatherRepository.csv')

from google.colab import drive
drive.mount('/content/drive')

num_duplicates = df.duplicated().sum()
print(f"/n Number of duplicate rows : {num_duplicates}")

avg_temp_by_country = ( df.groupby('country')['temperature_celsius'] .mean().sort_values(ascending=False))
print("/n Average Temperature by Country (Top 5):")
print(avg_temp_by_country.head(5))

avg_temp = df['temperature_celsius'].mean()
print(avg_temp)

min_temp = df['temperature_celsius'].min()
print(min_temp)

max_temp = df['temperature_celsius'].max()
print(max_temp)

top_conditions = df['condition_text'].value_counts().head(3)
print(top_conditions)

df.sort_values('temperature_celsius')

df['location_name'].str.upper()

df.describe()

df.isnull().sum()

df_filtered = df[df['temperature_celsius'] > 25]
print(df_filtered)

df = df.sort_values(by='temperature_celsius', ascending=False)
print(df)

df.head(5)

df.tail(5)

df.info()

df.describe()

df.shape

city_avg = df.groupby('country')['temperature_celsius'].mean()
print(city_avg)

df_filtered = df[(df['temperature_celsius'] > 25) & (df['temperature_fahrenheit'] > 25)]
print(df_filtered)

df = df.dropna()
print(df)

df = df.fillna(0)
print(df)

city_avg = df.groupby('country')['temperature_celsius'].max()
print(city_avg)

city_avg = df.groupby('country')['temperature_celsius'].min()
print(city_avg)

df['moon_phase'] = df['moon_phase'].replace('Waxing Gibbous', 'waxing gibbous')
print(df)

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/GlobalWeatherRepository.csv')
print(data)

plt.bar(data['country'], data['temperature_celsius'], color='skyblue')
plt.title('country by temperature')
plt.xlabel('country')
plt.ylabel('temperature_celsius')
plt.show()

plt.plot(data['country'], data['temperature_celsius'], marker='o', color='green')
plt.title('country vs temperature_celsius')
plt.xlabel('country')
plt.ylabel('temperature_celsius')
plt.grid(True)
plt.show()

df = df.drop("timezone", axis=1)
print("\nAfter:\n", df)

df['temperature_fahrenheit plus 10']  = df['temperature_fahrenheit'] +10
print(df)

df.to_csv("cleaned_data.csv", index=False)

df = df.sort_values(by='humidity', ascending=False)
print(df)

plt.scatter(df['country'], df['humidity'], c=df['humidity'], cmap='coolwarm', s=100)
plt.title('humity vs contry')
plt.xlabel('country')
plt.ylabel('humidity')
plt.colorbar(label='Profit Intensity')
plt.grid(True)
plt.show()

df['condition_text'] = df['condition_text'].replace('Clear', 'clear')
print(df)

