# -*- coding: utf-8 -*-
"""milestone 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqFrnRH2UwyHGYl_DIsK-zje1jORty5L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv("/GlobalWeatherRepository.csv")

print("Dataset Overview:")
print(df.head())

print("\nMissing Values per Column:")
print(df.isnull().sum())

df = df.dropna(subset=['location_name', 'temperature_celsius'])
print(df)

if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    print(df)

print("\nDescriptive Statistics:")
print(df.describe())

top_hot = df.nlargest(5, 'temperature_celsius')[['location_name', 'last_updated', 'temperature_celsius']]
top_cold = df.nsmallest(5, 'temperature_celsius')[['location_name', 'last_updated', 'temperature_celsius']]
print(top_cold)
print(top_hot)

region_stats = df.groupby('country')['temperature_celsius'].agg(['mean', 'min', 'max', 'std']).reset_index()
print("\ncountry Temperature Summary:\n", region_stats)

corr = df.select_dtypes(include=['float64', 'int64']).corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

if 'last_updated' in df.columns:
    plt.figure(figsize=(10,5))
    sns.lineplot(x='last_updated', y='temperature_celsius', data=df)
    plt.title("Temperature Trend Over Time")
    plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(x='country', y='temperature_celsius', data=df)
plt.xticks(rotation=45)
plt.title("Temperature Distribution by Region")
plt.show()

if 'Latitude' in df.columns and 'Longitude' in df.columns:
    fig = px.scatter_mapbox(df, lat='Latitude', lon='Longitude',
                            color='Temperature', size='Temperature',
                            hover_name='Region', zoom=1,
                            mapbox_style='carto-positron',
                            title="Global Temperature Distribution")
    fig.show()

if 'Date' in df.columns:
    df['Month'] = df['Date'].dt.month
    monthly = df.groupby(['Region', 'Month'])['Temperature'].mean().reset_index()
    pivot = monthly.pivot('Region', 'Month', 'Temperature')
    plt.figure(figsize=(10,6))
    sns.heatmap(pivot, cmap='YlOrRd')
    plt.title("Average Monthly Temperature by Region")
    plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['temperature_celsius'], kde=True, bins=30, color='orange')
plt.title("Temperature Distribution")
plt.xlabel("Temperature (°C)")
plt.ylabel("Frequency")
plt.show()

corr = df.select_dtypes(include=['float64', 'int64']).corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(x='country', y='temperature_celsius', data=df, palette='coolwarm')
plt.xticks(rotation=45)
plt.title("Temperature Variability by Region")
plt.show()

if 'Date' in df.columns:
    df = df.sort_values('Date')
    df['Month'] = df['Date'].dt.month
    df['Year'] = df['Date'].dt.year

    monthly_avg = df.groupby(['Year','Month'])['Temperature'].mean().reset_index()
    monthly_avg['Date'] = pd.to_datetime(monthly_avg[['Year','Month']].assign(DAY=1))

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='viridis')
plt.title("Feature Correlation Heatmap")
plt.show()

plt.figure(figsize=(10,6))
sns.violinplot(x='location_name', y='temperature_celsius', data=df, palette='Set2', inner='box')
plt.title("Temperature Distribution per Region (Violin Plot)")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(x='temperature_celsius', y='humidity', hue='country', data=df)
plt.title('Temperature vs Humidity by Region')
plt.show()

if 'Latitude' in df.columns and 'Longitude' in df.columns:
    fig = px.scatter_geo(
        df, lat='Latitude', lon='Longitude', color='Temperature',
        hover_name='Region', size='Rainfall', projection="natural earth",
        title='Global Weather Distribution'
    )
    fig.show()

plt.figure(figsize=(10,6))
sns.histplot(df['wind_mph'], bins=30, kde=True, color='orange')
plt.title('Wind Speed Distribution')
plt.xlabel('Wind Speed (km/h)')
plt.ylabel('Frequency')
plt.show()

sns.pairplot(df[['temperature_celsius','humidity','wind_kph']], diag_kind='kde')
plt.suptitle('Pairwise Comparison of Weather Variables', y=1.02)
plt.show()